// Initialize Google API
let googleAuthToken = null;

// Handle messages from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'syncWithGoogleCalendar') {
    syncWithGoogleCalendar(request.events)
      .then(result => {
        sendResponse({success: true, result: result});
      })
      .catch(error => {
        console.error('Error syncing with Google Calendar:', error);
        sendResponse({success: false, error: error.toString()});
      });
    return true;  // Required for async response
  }
});

// Function to authenticate with Google
async function authenticateWithGoogle() {
  return new Promise((resolve, reject) => {
    chrome.identity.getAuthToken({interactive: true}, function(token) {
      if (chrome.runtime.lastError) {
        reject(chrome.runtime.lastError);
        return;
      }

      if (token) {
        googleAuthToken = token;
        resolve(token);
      } else {
        reject(new Error('Failed to get auth token'));
      }
    });
  });
}

// Function to sync events with Google Calendar
async function syncWithGoogleCalendar(events) {
  try {
    // Get auth token if we don't have one
    if (!googleAuthToken) {
      await authenticateWithGoogle();
    }

    // Find or create a calendar for these events
    const calendarId = await findOrCreateCalendar('Intranet Events');

    // Batch create events
    const results = await batchCreateEvents(calendarId, events);

    return {
      calendarId: calendarId,
      createdEvents: results.length
    };
  } catch (error) {
    console.error('Error in syncWithGoogleCalendar:', error);
    throw error;
  }
}

// Function to find or create a calendar
async function findOrCreateCalendar(calendarName) {
  try {
    // First try to find an existing calendar
    const response = await fetch('https://www.googleapis.com/calendar/v3/users/me/calendarList', {
      headers: {
        'Authorization': 'Bearer ' + googleAuthToken
      }
    });

    const data = await response.json();

    // Look for our calendar
    const calendar = data.items.find(cal => cal.summary === calendarName);

    if (calendar) {
      return calendar.id;
    }

    // If not found, create a new calendar
    const createResponse = await fetch('https://www.googleapis.com/calendar/v3/calendars', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + googleAuthToken,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        summary: calendarName,
        description: 'Calendar for intranet events imported via Intranet Calendar Sync extension',
        timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
      })
    });

    const newCalendar = await createResponse.json();
    return newCalendar.id;
  } catch (error) {
    console.error('Error finding/creating calendar:', error);
    throw error;
  }
}

// Function to batch create events in Google Calendar
async function batchCreateEvents(calendarId, events) {
  const results = [];

  // Process events in batches (could implement actual batch API if needed)
  for (const event of events) {
    try {
      if (!event.startTime || !event.endTime) continue;

      const summary = `${event.group} - ${event.course}`;
      const description = `Activity: ${event.activity}
Group: ${event.group}
Room: ${event.room}
Capacity: ${event.capacity}

Generated by Intranet Calendar Sync`;

      const calendarEvent = {
        summary: summary,
        location: `Room ${event.room}`,
        description: description,
        start: {
          dateTime: event.startTime,
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
        },
        end: {
          dateTime: event.endTime,
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
        },
        // Add color based on event type (you can customize these)
        colorId: getEventColorId(event.group)
      };

      const response = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events`, {
        method: 'POST',
        headers: {
          'Authorization': 'Bearer ' + googleAuthToken,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(calendarEvent)
      });

      const result = await response.json();
      results.push(result);
    } catch (error) {
      console.error('Error creating event:', error);
      // Continue with other events even if one fails
    }
  }

  return results;
}

// Function to determine color based on group
function getEventColorId(group) {
  // Google Calendar color IDs (1-11):
  // 1: Lavender, 2: Sage, 3: Grape, 4: Flamingo, 5: Banana
  // 6: Tangerine, 7: Peacock, 8: Graphite, 9: Blueberry, 10: Basil, 11: Tomato

  if (!group) return '1'; // Default to Lavender

  // Extract group number from format like "G0", "G1", etc.
  const groupNum = parseInt(group.replace('G', ''));

  // Use modulo to cycle through colors
  const colorId = (groupNum % 11) + 1;

  return colorId.toString();
}
